name: create-release.yml
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - name: install gcc
        run: |
          sudo apt update
          sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: Build
        run: cargo build --release --target aarch64-unknown-linux-gnu
      - name: package
        run: cargo deb --target aarch64-unknown-linux-gnu -p radio-station